from research_user_interest.model.get_data import GetTextfileTask
from research_user_interest.model.preprocess import CleanBodyTask
from research_user_interest.model.get_pretrain_vector import GetPretarinedVectorTask
from research_user_interest.model.extract_text_info import AddNoumColTask
from research_user_interest.model.check import CheckNewsTitleTask
from research_user_interest.model.make_graph import MakeTsneTask
from research_user_interest.model.do_annoy import GetSimilarArticleByAnnoyTask